### ISSUE TITLE
`throttle` in main __init__ not used or passed on to parent class

### ISSUE THREAD

**Issue by shmulvad** [eadwinCode/django-ninja-extra#169] opened 2024-08-07 10:20 UTC
Consider the following code:

https://github.com/eadwinCode/django-ninja-extra/blob/d826d942d80f71adfe538d2b9cd551b3352ee650/ninja_extra/main.py#L37-L80

You will notice that `throttle` is not actually used, for example by being passed to the __init__ method of the parent class. I know Django Ninja Extra has special throttling built in, but I'd prefer to use the native Django Ninja throttling.

![Screenshot 2024-08-07 at 18 21 01](https://github.com/user-attachments/assets/f7a6fca2-402e-4eb3-bc7d-f0cd6f493b07)

**Comment by eadwinCode** [comment] 2024-08-07 11:44
@shmulvad Thanks for this observation... I will fix this shortly

**Comment by eadwinCode** [comment] 2024-08-08 21:58
@shmulvad can you close this if the issue is resolved?

**Closed** 2024-08-09 01:09 UTC
