### ISSUE TITLE
Permissions are verified before authentication.

### ISSUE THREAD

**Issue by airddm** [eadwinCode/django-ninja-extra#212] opened 2024-12-03 14:07 UTC
### How to reproduce.

```python
from typing import Any

from django.http import HttpRequest
from ninja_extra import permissions, NinjaExtraAPI, api_controller, http_get
from ninja_jwt.authentication import AsyncJWTAuth
from ninja_jwt.controller import NinjaJWTDefaultController

api = NinjaExtraAPI()
api.register_controllers(NinjaJWTDefaultController)


class MyAuth(AsyncJWTAuth):
    async def authenticate(self, request: HttpRequest, token: str) -> Any:
        # This method will be called after MyPerm.has_permission calling.
        # Expected behavior: Authenticate should be called firstly.
        return await self.async_jwt_authenticate(request, token)


class MyPerm(permissions.BasePermission):
    def has_permission(self, request, controller):
        return request.user.groups.filter(name="MyGroup").exists()


@api_controller('', tags=['My Operations'], auth=MyAuth(), permissions=[MyPerm])
class MyAPIController:

    @http_get("/path")
    async def get_operation(self):
        return {"ok": "ok"}

api.register_controllers(MyAPIController)
```

### Issue: 

`MyPerm.has_permissions` is called before  `AsyncJWTAuth.authenticate` 
so when  `MyPerm.has_permissions` is called, the `request.user` will be always `AnonymousUser` because `AsyncJWTAuth.authenticate` has not been called yet.

### Expected behavior

`AsyncJWTAuth.authenticate` is called first to initialize `request.user`, and then `BasePermission.has_permission`

**Comment by eadwinCode** [comment] 2024-12-04 05:27
@airddm Thanks🙏 for bringing this to my notice. It was an oversight

**Comment by eadwinCode** [comment] 2024-12-04 05:30
I have also published a new release, please let me know if the problem is resolved at your end.

**Comment by eadwinCode** [comment] 2024-12-04 13:35
@Tragio can you give an example source code that resulted to the error?  Your current example is not showing anything that relates to user_id.

**Comment by Tragio** [comment] 2024-12-04 15:56
Interesting, so the problem it is not picking `GET /me` only if I remove the other dynamic ones 🤔 

```py
import uuid

from ninja_extra import (
    api_controller,
    http_delete,
    http_get,
    status,
)


@api_controller("/users", tags=["User"])
class UserAPI:
    @http_get("/me")
    def get_current_user(self, request):
        return {"debug": "ok"}

    @http_get("/{user_id}")
    def get_user(self, request, user_id: uuid.UUID):
        return {"debug": "ok"}

    @http_delete("/{user_id}", response={status.HTTP_204_NO_CONTENT: None})
    def delete_user_from_clinic(self, request, user_id: uuid.UUID, token: str):
        return {"debug": "ok"}


```

**Comment by eadwinCode** [comment] 2024-12-04 16:46
@Tragio you have two endpoints with there same path configuration, `get_current_user` and `get_user` has the same path configuration. so when you call  `get_current_user`, django will call `get_user` cause in set up hierarchy `get_user` comes last. 

My solution for your
```python
@api_controller("/users", tags=["User"])
class UserAPI:
    @http_get("/currrent-user")
    def get_current_user(self, request):
        return {"debug": "ok"}

    @http_get("/{user_id}")
    def get_user(self, request, user_id: uuid.UUID):
        return {"debug": "ok"}
    
    @http_delete("/{user_id}", response={status.HTTP_204_NO_CONTENT: None})
    def delete_user_from_clinic(self, request, user_id: uuid.UUID, token: str):
        return {"debug": "ok"}
```

**Comment by eadwinCode** [comment] 2024-12-04 16:46
Also, was this working before the upgrade?

**Comment by airddm** [comment] 2024-12-05 08:51
> I have also published a new release, please let me know if the problem is resolved at your end.

It works ! Thank you very much :+1:

**Comment by Tragio** [comment] 2024-12-05 09:51
@eadwinCode it was working before, that is why I was confused with the behaviour 😅 I thought it respected the order that I had 🤔

**Comment by eadwinCode** [comment] 2024-12-05 10:05
@Tragio that's interesting I will look into it again, I can't remember making changes to the route models.

But what version were you on before the upgrade?

**Comment by Tragio** [comment] 2024-12-05 10:15
@eadwinCode I was on the version 0.21.4, when I upgraded to 0.21.6 it started with that problem 🤔

**Comment by eadwinCode** [comment] 2024-12-05 10:56
@Tragio I will create a fix for this shortly, I have seen what caused it

**Comment by eadwinCode** [comment] 2024-12-05 11:18
@Tragio https://github.com/eadwinCode/django-ninja-extra/pull/214

**Comment by eadwinCode** [comment] 2024-12-05 11:20
@Tragio You can pull the latest release in 15 minutes, that should solve it.

**Comment by Tragio** [comment] 2024-12-05 11:31
@eadwinCode already tested, it is working. You're amazing, thank you very much ❤️

**Comment by eadwinCode** [comment] 2024-12-05 12:11
Awesome... Thanks for reporting this

**Closed** 2024-12-05 21:36 UTC
